### PR TITLE
Memory cleanup for static

### PR DESCRIPTION
**Pull request by dmpriso**
Possible fixes for #68

### CODE REVIEW

**Comment by kozlovic** [comment]
@dmpriso Please have a look at #70 to see if it solves your issue.

I took from your PR the call to `nats_ReleaseThreadMemory()` from the `_threadStart` function to reclaim thread-local storage from threads created by the library. There is one example where we create a user thread and perform NATS calls, so I call this function there.

But unlike in your PR, this function is not restricted to static library use. Any thread that the library creates needs to be cleaned-up, and on non Windows build, that was not happening at all (except for the main thread).

I also replaced the gcc's destructor and DllMain with `atexit()` which apparently serves the same purpose. I have verified that the final cleanup is invoked in all cases (examples statically or dynamically linked). The tests running with valgrind do not show any memory leak or still reachable memory. The good thing about this approach is that, as you can see, there is no need for the user to call any call, regardless if using the library dynamically or statically.

Please let me know if PR #70 works for you. I will obviously credit you in the release notes since you have reported the issue and proposed a fix for that. Thanks again!

**Comment by kozlovic** [comment]
By the way, I made 2 commits (the last being for the doc) so that code review can be simpler. Check the 1st commit for code-only changes: https://github.com/nats-io/cnats/pull/70/commits/a4f7830f75573c3412cec34915d25804cbd66342.

Also, in the future if you submit a PR, I would appreciate if you could replace tabs with 4 spaces to match the rest of the project. Thanks!

**Comment by dmpriso** [comment]
@kozlovic I ran my own unit tests of our cnats integration and they do not leak any more with your PR #70. Global cleanup works correctly. As you already mentioned, I still need to call `nats_ReleaseThreadMemory()` from my own threads where I call nats functions in order to prevent all leaks.

While I don't use the shared library myself (as of now), I'd suggest to add `DllMain()` again for windows builds because with a `DllMain()` it is possible to do that per-thread cleanup automatically for threads created outside of the DLL. With your PR #70, existing users which are using the shared library on windows now need to call `nats_ReleaseThreadMemory()` - it is kind of a break of existing code which now leaks where it didn't leak before.

**Comment by kozlovic** [comment]
@dmpriso Thanks for checking and you are right about `DllMain`. I have put it back just for the thread_detach case. For users on Windows using the dynamic library, this PR will result in identical behavior than before.

However, as I state in the comment, users that want to write portable applications that work the same if statically or dynamically linked, they should call `nats_ReleaseThreadMemory()` on the threads they create. In case of dynamic library, it means that `nats_ReleaseThreadMemory()` may be called twice per thread (one from user, one internally), but that's ok since this call does nothing if the thread local storage has already been freed.

Thanks again for your help! I am closing this PR in favor of PR #70.

**Pull request closed without merging**
